services:
  rag-app:
    build: .
    container_name: rag-app
    command: ["python", "main.py"]
    volumes:
      - ./data:/app/data
    working_dir: /app
    depends_on:
      - mongo
      - postgres
      - ollama
    networks:
      - rag-net
    environment:
      - MONGO_URI=mongodb://user123:password123@mongo:27017/
      - DATA_DIR=/app/data
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_DB=embedding_db
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=nomic-embed-text
      - EMBEDDING_DIM=768
      - GENERATION_MODEL=phi3:mini

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - rag-net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user123
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - mongo_data:/data/db  # persistente DB

  postgres:
    image: pgvector/pgvector:pg17  # Prebuilt Postgres image with pgvector
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: embedding_db
    volumes:
      - postgres_data:/data/postgres_db
    networks:                    
        - rag-net

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - rag-net


networks:
  rag-net:
    driver: bridge

volumes:
  mongo_data:
  postgres_data:
  ollama_data: